workflows:
  plany-app:
    name: Build Plany Android
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - cd front  # Accès au sous-dossier front
      - flutter pub get
      - flutter build apk
    artifacts:
      - front/build/app/outputs/flutter-apk/app-release.apk