workflows:
  plany-android-build:
    name: Build Plany Android
    max_build_duration: 60
    environment:
      java: 17  # ← Ajout de Java 17 pour correspondre à votre version locale
      flutter: stable
    scripts:
      - name: Clean Flutter
        script: flutter clean
        working_directory: front

      - name: Generate .env file from Codemagic environment variables
        script: |
          echo "API_HOST=$API_HOST" > front/.env.staging
          echo "IMGUR_REFRESH_TOKEN=$IMGUR_REFRESH_TOKEN" >> front/.env.staging
          echo "IMGUR_CALLBACK_URL=$IMGUR_CALLBACK_URL" >> front/.env.staging
          echo "IMGUR_CLIENT_SECRET=$IMGUR_CLIENT_SECRET" >> front/.env.staging
          echo "IMGUR_CLIENT_ID=$IMGUR_CLIENT_ID" >> front/.env.staging

      - name: Setup Android signing
        script: |
          echo storePassword=$CM_KEYSTORE_PASSWORD > front/android/key.properties
          echo keyPassword=$CM_KEY_PASSWORD >> front/android/key.properties
          echo keyAlias=$CM_KEY_ALIAS >> front/android/key.properties
          echo storeFile=`pwd`/front/keystore.jks >> front/android/key.properties
          echo $CM_KEYSTORE | base64 --decode > front/keystore.jks

      - name: Fix keystore compatibility
        script: |
          # Vérifier la version Java
          echo "Java version used:"
          java -version
          
          # Convertir le keystore pour assurer la compatibilité
          keytool -importkeystore \
            -srckeystore front/keystore.jks \
            -destkeystore front/keystore_fixed.jks \
            -deststoretype JKS \
            -srcstorepass $CM_KEYSTORE_PASSWORD \
            -deststorepass $CM_KEYSTORE_PASSWORD \
            -noprompt
          
          # Remplacer l'ancien keystore
          mv front/keystore_fixed.jks front/keystore.jks
          
          # Vérifier que le keystore est lisible
          keytool -list -keystore front/keystore.jks -storepass $CM_KEYSTORE_PASSWORD

      - name: Verify key.properties content
        script: |
          echo "==== key.properties ===="
          cat front/android/key.properties
          echo "========================"

      - name: Get Flutter dependencies
        script: flutter pub get
        working_directory: front

      - name: Build AAB
        script: flutter build appbundle --release
        working_directory: front

    artifacts:
      - front/build/app/outputs/bundle/release/app-release.aab