workflows:
  build-app:
    name: Build Android
    environment:
      flutter: stable
    scripts:
      - cd front
      - flutter pub get
      - flutter build apk
    artifacts:
      - front/build/app/outputs/flutter-apk/app-release.apk
