workflows:
  plany-android-build:
    name: Build Plany Android
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
        working_directory: front

      - name: Build APK
        script: flutter build apk --release
        working_directory: front

    artifacts:
      - front/build/app/outputs/flutter-apk/app-release.apk
