services:
  api-gateway:
    build:
      context: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    networks:
      - plany-network
    depends_on:
      - auth-service
      - user-service
      - notification-service
      - partner-service
      - payment-service
      - plan-service
      - search-service

  auth-service:
    build:
      context: ./backend/auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    networks:
      - plany-network

  user-service:
    build:
      context: ./backend/user-service
    container_name: user-service
    ports:
      - "3002:3002"
    networks:
      - plany-network
    
  notification-service:
    build:
      context: ./backend/notification-service
    container_name: notification-service
    ports:
      - "3003:3003"
    networks:
      - plany-network

  partner-service:
    build:
      context: ./backend/partner-service
    container_name: partner-service
    ports:
      - "3004:3004"
    networks:
      - plany-network

  payment-service:
    build:
      context: ./backend/payment-service
    container_name: payment-service
    ports:
      - "3005:3005"
    networks:
      - plany-network

  plan-service:
    build:
      context: ./backend/plan-service
    container_name: plan-service
    ports:
      - "3006:3006"
    networks:
      - plany-network

  search-service:
    build:
      context: ./backend/search-service
    container_name: search-service
    ports:
      - "3007:3007"
    networks:
      - plany-network
    depends_on:
      - redis

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - plany-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - plany-network

networks:
  plany-network:
    driver: bridge

volumes:
  mongo-data:
