// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummy-Key-For-Development',
    appId: '1:123456789012:web:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '123456789012',
    projectId: 'plany-app',
    authDomain: 'plany-app.firebaseapp.com',
    storageBucket: 'plany-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummy-Key-For-Development-Android',
    appId: '1:123456789012:android:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '123456789012',
    projectId: 'plany-app',
    storageBucket: 'plany-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummy-Key-For-Development-iOS',
    appId: '1:123456789012:ios:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '123456789012',
    projectId: 'plany-app',
    storageBucket: 'plany-app.appspot.com',
    iosBundleId: 'com.example.plany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummy-Key-For-Development-macOS',
    appId: '1:123456789012:ios:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '123456789012',
    projectId: 'plany-app',
    storageBucket: 'plany-app.appspot.com',
    iosBundleId: 'com.example.plany',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummy-Key-For-Development-Windows',
    appId: '1:123456789012:windows:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '123456789012',
    projectId: 'plany-app',
    storageBucket: 'plany-app.appspot.com',
  );
}
