name: OSV-Scanner PR Scan

# Change "main" to your default branch if you use a different name, i.e. "master"
on:
  pull_request:
    branches: [main, develop]
  merge_group:
    branches: [main, develop]
  push:
    branches: [main, develop]
    paths: ["back/**", ".github/workflows/osv-scanner.yml"]

permissions:
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read

jobs:
  scan-pr:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.0.3"
